[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "ferreus_rbf"
version = "0.3.0"
readme = "README.md"
license = "MIT"
authors = [{ name = "Daniel Owen", email = "daniel.owen@live.com.au"}]
description = "Fast, memory efficient radial basis function (RBF) interpolation library"
requires-python = ">=3.8"
keywords = [
    "rbf", 
    "radial-basis-function", 
    "isosurface", 
    "interpolation"
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]

dependencies = [
    "numpy >= 1.16.0",
]

[tool.maturin]
profile = "release"
features = ["pyo3/extension-module"]

[project.urls]
Homepage = "https://github.com/graphic-goose/ferreus_rbf_rs/"
Documentation = "https://graphic-goose.github.io/ferreus_rbf_rs/ferreus_rbf/"
